#include "festruct.h"

#define GETELEMENTLAGRANGEFE(x)\
    template<>\
    LagrangeFE<x>* FEStruct::GetElementFor () {return NAMELAGRANGEFE(x);}

#define NEWLAGRANGEFE(x) NAMELAGRANGEFE(x) (new LagrangeFE<x>())

FEStruct::FEStruct () :
    NEWLAGRANGEFE (VTK_EMPTY_CELL),
    NEWLAGRANGEFE (VTK_LINE),
    NEWLAGRANGEFE (VTK_VERTEX),
    NEWLAGRANGEFE (VTK_TRIANGLE),
    NEWLAGRANGEFE (VTK_QUADRATIC_EDGE),
    NEWLAGRANGEFE (VTK_QUADRATIC_TRIANGLE)
{}

FEStruct::~FEStruct ()
{
    delete NAMELAGRANGEFE (VTK_EMPTY_CELL);
    delete NAMELAGRANGEFE (VTK_LINE);
    delete NAMELAGRANGEFE (VTK_VERTEX);
    delete NAMELAGRANGEFE (VTK_TRIANGLE);
    delete NAMELAGRANGEFE (VTK_QUADRATIC_EDGE);
    delete NAMELAGRANGEFE (VTK_QUADRATIC_TRIANGLE);
}

GETELEMENTLAGRANGEFE (VTK_EMPTY_CELL);
GETELEMENTLAGRANGEFE (VTK_LINE);
GETELEMENTLAGRANGEFE (VTK_VERTEX);
GETELEMENTLAGRANGEFE (VTK_TRIANGLE);
GETELEMENTLAGRANGEFE (VTK_QUADRATIC_EDGE);
GETELEMENTLAGRANGEFE (VTK_QUADRATIC_TRIANGLE);
