#ifndef UNDEF_MACROS_H
#define UNDEF_MACROS_H

#undef TO_STRING_SPECIALIZATION
#undef CASE
#undef END_CASE_DEFAULT

#undef FROM_STRING_SPECIALIZATION
#undef SIMPLE_IF
#undef ELSEIF
#undef ELSE

#undef CONVERT_SPECIALIZATION
#undef CASE_CONVERT
#undef END_CASE_DEFAULT_CONVERT

#endif // UNDEF_MACROS_H
