#ifndef SRC_ENUMS_UNDEF_MACROS_HPP
#define SRC_ENUMS_UNDEF_MACROS_HPP

#undef TO_STRING_SPECIALIZATION
#undef CASE
#undef END_CASE_DEFAULT

#undef FROM_STRING_SPECIALIZATION
#undef SIMPLE_IF
#undef ELSEIF
#undef ELSE

#undef CONVERT_SPECIALIZATION
#undef CASE_CONVERT
#undef END_CASE_DEFAULT_CONVERT

#endif /* SRC_ENUMS_UNDEF_MACROS_HPP */
