#include "tags_enums.h"
#include "../def_macros.h"

FROM_STRING_SPECIALIZATION(PHYS)
{
    SIMPLE_IF(WALL);
    ELSEIF(INLET);
    ELSEIF(OUTLET);
    ELSEIF(DOMAIN);
    ELSEIF(DEFAULT);
    ELSE(NONE);
}

TO_STRING_SPECIALIZATION(PHYS)
{
    CASE(WALL);
    CASE(INLET);
    CASE(OUTLET);
    CASE(DOMAIN);
    END_CASE_DEFAULT(NONE);
}

TO_STRING_SPECIALIZATION(INTER)
{
    CASE(IN);
    CASE(OUT);
    CASE(MIXED);
    END_CASE_DEFAULT(UNKNOW);
}

FROM_STRING_SPECIALIZATION(INTER)
{
    SIMPLE_IF(IN);
    ELSEIF(OUT);
    ELSEIF(MIXED);
    ELSEIF(DEFAULT);
    ELSE(UNKNOWN);
}

#include "../undef_macros.h"
