#include "supersolver_enums.hpp"

#include "../def_macros.hpp"

TO_STRING_SPECIALIZATION (SCH_T)
{
    CASE (EULER_EXPLICIT);
    CASE (EULER_IMPLICIT);
    CASE (TVD_RK_2);
    CASE (TVD_RK_4);
    CASE (NEWMARK_SCHEME);
    END_CASE_DEFAULT (NO_TIME);
}

FROM_STRING_SPECIALIZATION (SCH_T)
{
    SIMPLE_IF (NO_TIME);
    ELSEIF (EULER_IMPLICIT);
    ELSEIF (EULER_EXPLICIT);
    ELSEIF (TVD_RK_2);
    ELSEIF (TVD_RK_4);
    ELSEIF (NEWMARK_SCHEME);
    ELSE (NO_TIME);
}

TO_STRING_SPECIALIZATION (ITEM_T)
{
    CASE (PHI_PHI);
    CASE (DAMPING_PHI_PHI);
    CASE (GRAD_GRAD);
    CASE (SECOND_MEMBER);
    CASE (DIRICHLET_BOUNDARY);
    CASE (NEUMANN_BOUNDARY);
    CASE (DIRICHLET_BOUNDARY_SBM);
    CASE (NEUMANN_BOUNDARY_SBM);
    END_CASE_DEFAULT (EMPTY);
}

FROM_STRING_SPECIALIZATION (ITEM_T)
{
    SIMPLE_IF (PHI_PHI);
    ELSEIF (DAMPING_PHI_PHI);
    ELSEIF (GRAD_GRAD);
    ELSEIF (SECOND_MEMBER);
    ELSEIF (DIRICHLET_BOUNDARY);
    ELSEIF (NEUMANN_BOUNDARY);
    ELSEIF (DIRICHLET_BOUNDARY_SBM);
    ELSEIF (NEUMANN_BOUNDARY_SBM);
    ELSE (EMPTY);
}

#include "../undef_macros.hpp"
